CREATE TABLE [dbo].[Role](
    [Id]   INT           NOT NULL IDENTITY(1, 1),
    [Name] NVARCHAR(128) NOT NULL,

    CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [UX_Role_Name] UNIQUE NONCLUSTERED ([Name])
);
GO
